//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GryphonSecurity_v2_2.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GryphonSecurity_v2_2.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string AppBarButtonText {
            get {
                return ResourceManager.GetString("AppBarButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string AppBarMenuItemText {
            get {
                return ResourceManager.GetString("AppBarMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gryphon Security.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm Report.
        /// </summary>
        public static string LayoutTitleAlarmReport {
            get {
                return ResourceManager.GetString("LayoutTitleAlarmReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string LayoutTitleLogin {
            get {
                return ResourceManager.GetString("LayoutTitleLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigation.
        /// </summary>
        public static string LayoutTitleNavigation {
            get {
                return ResourceManager.GetString("LayoutTitleNavigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string LayoutTitleRegister {
            get {
                return ResourceManager.GetString("LayoutTitleRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan NFC.
        /// </summary>
        public static string LayoutTitleScanNFC {
            get {
                return ResourceManager.GetString("LayoutTitleScanNFC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error when tryed to login.
        /// </summary>
        public static string LoginError {
            get {
                return ResourceManager.GetString("LoginError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending alarmreports: .
        /// </summary>
        public static string PendingAlarmReports {
            get {
                return ResourceManager.GetString("PendingAlarmReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending NFC: .
        /// </summary>
        public static string PendingNFC {
            get {
                return ResourceManager.GetString("PendingNFC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send pending.
        /// </summary>
        public static string PendingSendPendingButton {
            get {
                return ResourceManager.GetString("PendingSendPendingButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The report was not sent.
        /// </summary>
        public static string ReportAlarmReportFailed {
            get {
                return ResourceManager.GetString("ReportAlarmReportFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm report did not get saved on phone.
        /// </summary>
        public static string ReportAlarmReportLocalStorageFailed {
            get {
                return ResourceManager.GetString("ReportAlarmReportLocalStorageFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm report did get saved on phone.
        /// </summary>
        public static string ReportAlarmReportLocalStorageSuccess {
            get {
                return ResourceManager.GetString("ReportAlarmReportLocalStorageSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The report was sent .
        /// </summary>
        public static string ReportAlarmReportSuccess {
            get {
                return ResourceManager.GetString("ReportAlarmReportSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apprehended person.
        /// </summary>
        public static string ReportApprehendedPerson {
            get {
                return ResourceManager.GetString("ReportApprehendedPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrived at:.
        /// </summary>
        public static string ReportArrivedAtTB {
            get {
                return ResourceManager.GetString("ReportArrivedAtTB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Burglary vandalism.
        /// </summary>
        public static string ReportBurglaryVandalism {
            get {
                return ResourceManager.GetString("ReportBurglaryVandalism", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel during emergency.
        /// </summary>
        public static string ReportCancelsDuringEmergency {
            get {
                return ResourceManager.GetString("ReportCancelsDuringEmergency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string ReportCity {
            get {
                return ResourceManager.GetString("ReportCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control center.
        /// </summary>
        public static string ReportControlCenter {
            get {
                return ResourceManager.GetString("ReportControlCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cover made.
        /// </summary>
        public static string ReportCoverMade {
            get {
                return ResourceManager.GetString("ReportCoverMade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer name.
        /// </summary>
        public static string ReportCustomerName {
            get {
                return ResourceManager.GetString("ReportCustomerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer name:.
        /// </summary>
        public static string ReportCustomerNameTB {
            get {
                return ResourceManager.GetString("ReportCustomerNameTB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer not found.
        /// </summary>
        public static string ReportCustomerNotFound {
            get {
                return ResourceManager.GetString("ReportCustomerNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer number.
        /// </summary>
        public static string ReportCustomerNumber {
            get {
                return ResourceManager.GetString("ReportCustomerNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date:.
        /// </summary>
        public static string ReportDateTB {
            get {
                return ResourceManager.GetString("ReportDateTB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done:.
        /// </summary>
        public static string ReportDoneTB {
            get {
                return ResourceManager.GetString("ReportDoneTB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string ReportError {
            get {
                return ResourceManager.GetString("ReportError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill out the required boxes.
        /// </summary>
        public static string ReportFillSpaces {
            get {
                return ResourceManager.GetString("ReportFillSpaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guard radioed date:.
        /// </summary>
        public static string ReportGuardRadioedDateTB {
            get {
                return ResourceManager.GetString("ReportGuardRadioedDateTB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guard radioed from:.
        /// </summary>
        public static string ReportGuardRadioedFromTB {
            get {
                return ResourceManager.GetString("ReportGuardRadioedFromTB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guard radioed to:.
        /// </summary>
        public static string ReportGuardRadioedToTB {
            get {
                return ResourceManager.GetString("ReportGuardRadioedToTB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installer.
        /// </summary>
        public static string ReportInstaller {
            get {
                return ResourceManager.GetString("ReportInstaller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NFC disabled, Restart the App with NFC enabled.
        /// </summary>
        public static string ReportNFCDisabled {
            get {
                return ResourceManager.GetString("ReportNFCDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing to report.
        /// </summary>
        public static string ReportNothingToReport {
            get {
                return ResourceManager.GetString("ReportNothingToReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string ReportOther {
            get {
                return ResourceManager.GetString("ReportOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phonenumber.
        /// </summary>
        public static string ReportPhonenumber {
            get {
                return ResourceManager.GetString("ReportPhonenumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remark.
        /// </summary>
        public static string ReportRemark {
            get {
                return ResourceManager.GetString("ReportRemark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string ReportSaveReportButton {
            get {
                return ResourceManager.GetString("ReportSaveReportButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string ReportSearchForCustomer {
            get {
                return ResourceManager.GetString("ReportSearchForCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send report.
        /// </summary>
        public static string ReportSendReportButton {
            get {
                return ResourceManager.GetString("ReportSendReportButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff error.
        /// </summary>
        public static string ReportStaffError {
            get {
                return ResourceManager.GetString("ReportStaffError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street and house number.
        /// </summary>
        public static string ReportStreetAndHouseNumber {
            get {
                return ResourceManager.GetString("ReportStreetAndHouseNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technical error.
        /// </summary>
        public static string ReportTechnicalError {
            get {
                return ResourceManager.GetString("ReportTechnicalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown reason.
        /// </summary>
        public static string ReportUnknownReason {
            get {
                return ResourceManager.GetString("ReportUnknownReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window door closed.
        /// </summary>
        public static string ReportWindowDoorClosed {
            get {
                return ResourceManager.GetString("ReportWindowDoorClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip code.
        /// </summary>
        public static string ReportZipCode {
            get {
                return ResourceManager.GetString("ReportZipCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zone.
        /// </summary>
        public static string ReportZone {
            get {
                return ResourceManager.GetString("ReportZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready to scan NFC tag.
        /// </summary>
        public static string ScanNFCReady {
            get {
                return ResourceManager.GetString("ScanNFCReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time of scan.
        /// </summary>
        public static string ScanNFCScanTime {
            get {
                return ResourceManager.GetString("ScanNFCScanTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag address.
        /// </summary>
        public static string ScanNFCTagAddress {
            get {
                return ResourceManager.GetString("ScanNFCTagAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NFC scan saved on phone.
        /// </summary>
        public static string ScanNFCTempStorage {
            get {
                return ResourceManager.GetString("ScanNFCTempStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for user.
        /// </summary>
        public static string SearchUserRegisterButton {
            get {
                return ResourceManager.GetString("SearchUserRegisterButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string UserAddress {
            get {
                return ResourceManager.GetString("UserAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User created.
        /// </summary>
        public static string UserCreated {
            get {
                return ResourceManager.GetString("UserCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firstname.
        /// </summary>
        public static string UserFirstname {
            get {
                return ResourceManager.GetString("UserFirstname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string UserId {
            get {
                return ResourceManager.GetString("UserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lastname.
        /// </summary>
        public static string UserLastname {
            get {
                return ResourceManager.GetString("UserLastname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string UserLoginButton {
            get {
                return ResourceManager.GetString("UserLoginButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username or password is wrong.
        /// </summary>
        public static string UsernamePasswordError {
            get {
                return ResourceManager.GetString("UsernamePasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not created.
        /// </summary>
        public static string UserNotCreated {
            get {
                return ResourceManager.GetString("UserNotCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not found, wrong id.
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string UserPassword {
            get {
                return ResourceManager.GetString("UserPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string UserPasswordConfirm {
            get {
                return ResourceManager.GetString("UserPasswordConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords was not the same.
        /// </summary>
        public static string UserPasswordNotEquel {
            get {
                return ResourceManager.GetString("UserPasswordNotEquel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phonenumber.
        /// </summary>
        public static string UserPhonenumber {
            get {
                return ResourceManager.GetString("UserPhonenumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string UserRegisterButton {
            get {
                return ResourceManager.GetString("UserRegisterButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in registration.
        /// </summary>
        public static string UserRegistrationError {
            get {
                return ResourceManager.GetString("UserRegistrationError", resourceCulture);
            }
        }
    }
}
